version: "2"

services:
  sentry:
    image: sentry
    ports:
      - "80:9000"
    links:
      - redis
      - postgres
    environment:
      - SENTRY_SECRET_KEY
    volumes:
      - sentry-data:/var/lib/sentry/files

  cron:
    image: sentry
    links:
      - redis
      - postgres
    environment:
      - SENTRY_SECRET_KEY
    volumes:
      - sentry-data:/var/lib/sentry/files
    command: run cron

  worker:
    image: sentry
    links:
      - redis
      - postgres
    environment:
      - SENTRY_SECRET_KEY
    volumes:
      - sentry-data:/var/lib/sentry/files
    command: run worker

  redis:
    image: redis
  # nginx:
  #   build: nginx/.
  #   depends_on:
  #     - sentry
  #   ports:
  #     - "80:80"
  #     - "443:443"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: secret
      PGDATA : /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  sentry-data:
  postgres-data:
